### PR TITLE
Can't Follow HTTP Redirects

### PR DESCRIPTION
**Pull request by cnchanning**
res.statusCode 3xx will throw error

### CODE REVIEW

**Comment by mschaaf** [comment]
Thanks for the patch, it doesn't speak anything against a merge, but I don't see a redirect on downloading. Could you please tell me from and to what url it redirects? Thank you for your help.

**Comment by cnchanning** [comment]
In china,many Internet Service Provider will redirect to his cache in order to save export-bandwidth. :-(
(e.g dl.node-webkit.org/v0.10.5/node-webkit-v0.10.5-osx-x64.zip redirect to http://119.80.188.6:81/1Q2W3E4R5T6Y7U8I9O0P1Z2X3C4V5B/dl.node-webkit.org/v0.10.5/node-webkit-v0.10.5-osx-x64.zip)

**Comment by mschaaf** [comment]
Ok understand. Thanks for your help it will be in the next release.

**Comment by msalahat** [comment]
Just tested current version on github still not resolved
"dl.node-webkit.org" should be replaced with "dl.nwjs.io"

I have tested locally and it worked.

**Comment by mschaaf** [comment]
@msalahat This is a new issue because of the node-webkit renaming. Please open a new issue or better an pull request with the fix. thank you.

**Pull request merged**
